name: Test
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [ 8, 11 ]

    steps:
      - uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Test
        run: sbt test
