name: Test
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [ 8, 11 ]

    steps:
      - uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy/cache
          key: v2-${{ runner.os }}-ivy-${{ hashFiles('project/build.properties') }}-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            v2-${{ runner.os }}-ivy-

      - name: Cache coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: v2-${{ runner.os }}-coursier-${{ hashFiles('project/build.properties') }}-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            v2-${{ runner.os }}-coursier-

      - name: Test
        run: sbt test
