name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test
    strategy:
      matrix:
        scala: [ 2.13.x, 3.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '11'
          java-package: jdk

      - name: Cache
        uses: coursier/cache-action@v6

      - name: Lint
        run: sbt --client "++${{ matrix.scala }} scalafmtCheckAll"

      - name: Compile
        run: sbt --client "++${{ matrix.scala }} Test/compile"

      - name: Test
        run: sbt --client "++${{ matrix.scala }} modules/test"

      - name: Integration Test
        env:
          CHROME_PATH: /usr/bin/google-chrome
        run: sbt --client "++${{ matrix.scala }} integrationTests/test"
